export const LOCAL_WEATHER_REQUEST = "LOCAL_WEATHER_REQUEST";
export const LOCAL_WEATHER_SUCCESS = "LOCAL_WEATHER_SUCCESS";
export const LOCAL_WEATHER_ERROR = "LOCAL_WEATHER_ERROR";
export const CURRENT_WEATHER_REQUEST = "CURRENT_WEATHER_REQUEST";
export const CURRENT_WEATHER_SUCCESS = "CURRENT_WEATHER_SUCCESS";
export const CURRENT_WEATHER_ERROR = "CURRENT_WEATHER_ERROR";
export const ADD_FAVORITE_CITY = "ADD_FAVORITE_CITY";
